"""Created Feedback, Appointment and Products Models

Revision ID: 4d6f38dce9e0
Revises: f2bb71b91e24
Create Date: 2023-11-25 07:36:50.861757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6f38dce9e0'
down_revision = 'f2bb71b91e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phonenumber', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('vehicle_make', sa.String(), nullable=True),
    sa.Column('vehicle_model', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.Column('time_frame', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phonenumber', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('vehicle_make', sa.String(), nullable=True),
    sa.Column('vehicle_no', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('appointment')
    op.drop_table('feedback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phonenumber', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('vehicle_make', sa.VARCHAR(), nullable=True),
    sa.Column('vehicle_no', sa.INTEGER(), nullable=True),
    sa.Column('service', sa.VARCHAR(), nullable=True),
    sa.Column('appointment_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phonenumber', sa.VARCHAR(), nullable=True),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('service', sa.VARCHAR(), nullable=True),
    sa.Column('vehicle_make', sa.VARCHAR(), nullable=True),
    sa.Column('vehicle_model', sa.INTEGER(), nullable=True),
    sa.Column('appointment_date', sa.DATETIME(), nullable=True),
    sa.Column('time_frame', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feedbacks')
    op.drop_table('appointments')
    # ### end Alembic commands ###
